puma_node:
  ros__parameters:
    sim_mode: true
    log_info: false
    target_marker_visible: true
    fsl_flag: true
    fsl_speed: 10.0
    default_max_speed: 3.0
    acc_speed: 2.0
    skidpad_speed: 2.0
    ebs_speed: 2.0
    lookahead_time: 0.5
    tau: 0.05
    kv: 0.2
    curvature_gain: 0.9
    kp: 0.11
    ki: 0.005
    kd: 0.0