name: CI

on:
  push:
    branches: [ "dockerization" ]
  pull_request:
    branches: [ "dockerization" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install ROS build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            git

      - name: Initialize rosdep
        run: |
          sudo rosdep init || true
          rosdep update

      - name: Clone external ROS packages
        run: |
          git clone -b dev https://github.com/FSLART/lart_msgs.git
          git clone https://github.com/FSLART/lart_common.git

      - name: Install ROS dependencies
        run: |
          source /opt/ros/humble/setup.bash
          rosdep install --from-paths . --ignore-src -r -y

      - name: Build workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install

      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test
          colcon test-result --all
